Development
greenfox-academy/chromediopside pull request #24
Opened 2017-06-20 13:18 UTC by Drumbumdeedum

2017-06-20 20:42 UTC, kondfox requested changes

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/GitinderApplication.java
> +public class GitinderApplication{
You should keep the space here between the function name and the `{`.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/controller/ProfileController.java
> +  public ResponseEntity<?> getProfile(@RequestHeader(name = "X-GiTinder-token", required=false) String token) {
The `X-GiTinder-token` header parameter should be a required parameter.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/controller/ProfileController.java
> +    }
Don't use if-else AND try-catch as well for the same checking. Choose one.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/datatransfer/LoginForm.java
> +  private String username, accessToken;
According to our styleguide, write these declarations in separate rows:
```
private String username;
private String accessToken;
```

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/datatransfer/TokenResponse.java
> +  private String status, token;
According to our styleguide, write these declarations in separate rows.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/service/LoginService.java
> +  private String missingValues(LoginForm loginForm) {
You should find a more general solution to check if you got all the required parameters. This solution works with just LoginForm objects and with just the already defined parameters.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/service/LoginService.java
> +  private String missingValues(LoginForm loginForm) {
Your solution should be able to work with other endpoint inputs and other required parameters as well.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +    GiTinderProfile giTinderProfile = new GiTinderProfile();
Use dependency injection whenever you can. There are some instantiations here where you could use dependency injection as well.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +          repositoryList) {
This should be in the previous line. You don't need a line break here.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +          languages) {
You don't need a line break here as well.

2017-06-20 20:42 UTC, kondfox commented on src/test/java/com/chromediopside/controller/ProfileControllerTest.java
> +            .andExpect(jsonPath("$").value(Matchers.hasKey("repos")));
You should check the`languages` key here as well.

2017-06-20 20:42 UTC, kondfox commented on src/test/java/com/chromediopside/service/ProfileServiceTest.java
> +    GiTinderProfile expectedProfile = new GiTinderProfile();
Use dependency injection wherever you can.

2017-06-20 20:42 UTC, kondfox commented on src/test/java/com/chromediopside/service/ProfileServiceTest.java
> +    expectedProfile.setLanguagesList(testLanguagesList);
Why don't you create a constructor for this purpose? That would be much easier to set up a new object.

2017-06-20 20:42 UTC, kondfox commented on src/main/resources/db/migration/V0_0_1__userinitialisation.sql
> +  FOREIGN KEY (LANGUAGE_ID) REFERENCES Language (languagename)
You don't have any Primary key defined here. You should. Either an autoincrement id or a composed key containing both columns.

2017-06-20 20:42 UTC, kondfox commented on src/main/java/com/chromediopside/model/Language.java
> +  private Set<GiTinderProfile> profileSet;
I'm not sure why do you need this set of profiles here. Why do you need this?

2017-06-21 08:59 UTC, kondfox requested changes

2017-06-21 08:59 UTC, kondfox commented on src/main/java/com/chromediopside/controller/LoginController.java
> +    return loginService.loginResponse(loginForm, appToken);
This should be better if you organize all functionality to your service layer. So you can generate the appToken from the accessToken in the service layer as well. Also the naming could be better here as well. instead of `loginService.loginResponse`, the `loginService.login` naming would be better, because your are not just giving a response, but you also do the login process as well.
So you could reduce this controller to the following code:
```
@PostMapping(value = "/login")
public ResponseEntity<?> login(@RequestBody LoginForm loginForm) {
  return loginService.login(loginForm);
}
```

2017-06-21 08:59 UTC, kondfox commented on src/main/java/com/chromediopside/controller/ProfileController.java
> +    }
Also organize these logics to the service layer.

2017-06-21 08:59 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +    Set<GiTinderProfile> profilesSet = selectingLanguage.getProfileSet();
Profiles shouldn't be a part of a Language. It doesn't belong there.
You should create a custom profile db query to get the 10 random profiles by language.

2017-06-22 07:32 UTC, Drumbumdeedum commented
Change pull request base to staged.

2017-06-22 07:32 UTC, merged