Staged
greenfox-academy/chromediopside pull request #53
Opened 2017-06-23 13:52 UTC by phorv1

2017-06-26 20:06 UTC, kondfox requested changes
a bunch of minor changes needed.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/controller/ProfileController.java
> +          @RequestHeader(name = "X-GiTinder-token") String accessToken) throws Exception {
we get an `appToken` here, not an `accessToken`. please change the naming.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/controller/ProfileController.java
> +          @PathVariable Map<String, Integer> pathVariable) throws Exception {
do we certainly need the `Map<String, Integer>` data structure here? I think this should work with a simple `Integer` as well.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/datatransfer/SwipeResponse.java
> +  boolean match_status;
according to our new specification this will be a `Match match` field here. but we can refactor it when the new implementation is ready.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/model/SwipeId.java
> +public class SwipeId implements Serializable{
missing space before `{`

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/model/Swiping.java
> +@IdClass(SwipeId.class)
`SwipeId` should be an inner class here, not an individual model.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/repository/ProfileRepository.java
> +  List<GiTinderProfile> selectTenRandomByLanguageName(String languageName);
I think you don't need this query anymore, you'll probably use your next query (below) for getting random-like entries.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/repository/ProfileRepository.java
> +  List<GiTinderProfile> selectBlocksOfTensByLanguageNameOrderByGivenParam(
although I respect that you gave a descriptive name here, there's probably a shorter one as well which is almost such descriptive ;)
so please find a shorter nam here if you can :)

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/repository/SwipeRepository.java
> +  @Query(value = "SELECT exists(select 1 from swiping where swiping_users_name = ?1 AND swiped_users_name = ?2)", nativeQuery = true)
format this query to multiple lines.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/PageService.java
> +    return profileRepository.selectBlocksOfTensOrderByGivenParam(randomSortingParam(), givenPageNumber);
for sake of easier debugging, separate this line to 2 lines. save the result to a variable first, then return with the variable.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +    return profileRepository.selectTenRandomByLanguageName(languageName);
you should use your other method here. the one that receives the random ordering parameter as well.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +  public void fetchAndSaveProfileOnLogin(LoginForm loginForm) {
We can solve this with less nested `if`s, so less complicated as well.
Let's talk about it during our next session.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +      return new ResponseEntity<Object>(pageService.setPage(pageNumber), HttpStatus.OK);
indentation

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +              (swipingUsersName, username);
we don't need a line break here. this should be in the previous line.

2017-06-26 20:06 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
> +      match_status = true;
indentation

2017-06-27 07:43 UTC, nosziszimi commented on src/main/java/com/chromediopside/repository/SwipeRepository.java
> +  @Query(value = "SELECT exists(select 1 from swiping where swiping_users_name = ?1 AND swiped_users_name = ?2)", nativeQuery = true)
:heavy_check_mark:

2017-06-27 07:43 UTC, nosziszimi commented on src/main/java/com/chromediopside/model/SwipeId.java
> +public class SwipeId implements Serializable{
:heavy_check_mark:

2017-06-27 07:43 UTC, nosziszimi commented on src/main/java/com/chromediopside/model/Swiping.java
> +@IdClass(SwipeId.class)
:heavy_check_mark:

2017-06-27 07:44 UTC, nosziszimi commented on src/main/java/com/chromediopside/datatransfer/SwipeResponse.java
> +  boolean match_status;
I will fix it with the implementation of the new specification

2017-06-27 07:46 UTC, nosziszimi commented on src/main/java/com/chromediopside/service/ProfileService.java
> +              (swipingUsersName, username);
:heavy_check_mark:

2017-06-27 07:48 UTC, nosziszimi commented on src/main/java/com/chromediopside/service/ProfileService.java
> +      match_status = true;
I think, that the indentation is correct here.

2017-06-28 10:35 UTC, kondfox requested changes

2017-06-28 10:35 UTC, kondfox commented on src/main/java/com/chromediopside/controller/LoginController.java
>      return loginService.login(loginForm, bindingResult);
Fix vulnerabilty here according to your new Trello card.

2017-06-28 10:35 UTC, kondfox commented on src/main/java/com/chromediopside/model/Match.java
> +  private Timestamp matched_at;
`matched_at` should be `matchedAt` in java.

2017-06-28 10:35 UTC, kondfox commented on src/main/java/com/chromediopside/service/PageService.java
> +    page.setCount(page.getProfiles().size());
Simplify this:
```
List<GiTinderProfile> profiles = listProfilesPerPage(givenPageNumber);
page.setProfiles(profiles);
page.setCount(profiles.size());
```

2017-06-28 10:35 UTC, kondfox commented on src/main/java/com/chromediopside/service/ProfileService.java
>    }
repair the following to work properly:
```
if (!(setLoginAndAvatar(gitHubClient, username, giTinderProfile) &&
         setReposAndLanguages(gitHubClient, username, giTinderProfile))) {
  giTinderProfile = null;
}
```

2017-06-28 12:28 UTC, nosziszimi commented on src/main/java/com/chromediopside/model/Match.java
> +  private Timestamp matched_at;
:heavy_check_mark:

2017-06-29 10:02 UTC, kondfox approved these changes
OK, but fix the commented tests as soon as possible

2017-06-29 10:17 UTC, merged